// ── Sprachbausteine Teil 1 – Section Config ────────────────────────────────
//
// HOW TO ADD A NEW TOPIC:
//   1. Create  sections/sprachbausteine-teil1/<topic-id>/quiz-data.js
//   2. Add a new entry to the topics[] array below
// ──────────────────────────────────────────────────────────────────────────

window.REGISTRY.push({
  id:       'sprachbausteine-teil1',
  title:    'Sprachbausteine Teil 1',
  subtitle: 'Das richtige Wort in die Lücke einsetzen (A, B oder C)',
  topics: [
    {
      id:          'meike',
      title:       'MEIKE',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--meike',
      dataFile:    'sections/sprachbausteine-teil1/meike/quiz-data.js',
    },
    {
      id:          'herr-martini',
      title:       'HERR MARTINI',
      description: 'Lückentext – Geschäftsbrief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--herr-martini',
      dataFile:    'sections/sprachbausteine-teil1/herr-martini/quiz-data.js',
    },
    {
      id:          'maria-timur',
      title:       'MARIA & TIMUR',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--maria-timur',
      dataFile:    'sections/sprachbausteine-teil1/maria-timur/quiz-data.js',
    },
    {
      id:          'redaktion',
      title:       'REDAKTION',
      description: 'Lückentext – Rundschreiben · 10 Lücken',
      quizId:      'sprachbausteine-teil1--redaktion',
      dataFile:    'sections/sprachbausteine-teil1/redaktion/quiz-data.js',
    },
    {
      id:          'ferdinand-1',
      title:       'FERDINAND 1',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--ferdinand-1',
      dataFile:    'sections/sprachbausteine-teil1/ferdinand-1/quiz-data.js',
    },
    {
      id:          'ferdinand-2',
      title:       'FERDINAND 2',
      description: 'Lückentext – Brief (Variante) · 10 Lücken',
      quizId:      'sprachbausteine-teil1--ferdinand-2',
      dataFile:    'sections/sprachbausteine-teil1/ferdinand-2/quiz-data.js',
    },
    {
      id:          'samira',
      title:       'SAMIRA',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--samira',
      dataFile:    'sections/sprachbausteine-teil1/samira/quiz-data.js',
    },
    {
      id:          'cosima',
      title:       'COSIMA',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--cosima',
      dataFile:    'sections/sprachbausteine-teil1/cosima/quiz-data.js',
    },
    {
      id:          'richard',
      title:       'RICHARD',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--richard',
      dataFile:    'sections/sprachbausteine-teil1/richard/quiz-data.js',
    },
    {
      id:          'heike',
      title:       'HEIKE',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--heike',
      dataFile:    'sections/sprachbausteine-teil1/heike/quiz-data.js',
    },
    {
      id:          'fabian',
      title:       'FABIAN',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--fabian',
      dataFile:    'sections/sprachbausteine-teil1/fabian/quiz-data.js',
    },
    {
      id:          'asja',
      title:       'ASJA',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--asja',
      dataFile:    'sections/sprachbausteine-teil1/asja/quiz-data.js',
    },
    {
      id:          'sabine-dobromil',
      title:       'SABINE (Dr. Dobromil)',
      description: 'Lückentext – Bewerbung · 10 Lücken',
      quizId:      'sprachbausteine-teil1--sabine-dobromil',
      dataFile:    'sections/sprachbausteine-teil1/sabine-dobromil/quiz-data.js',
    },
    {
      id:          'sabine-moosberger',
      title:       'SABINE (Dr. Moosberger)',
      description: 'Lückentext – Bewerbung (Variante) · 10 Lücken',
      quizId:      'sprachbausteine-teil1--sabine-moosberger',
      dataFile:    'sections/sprachbausteine-teil1/sabine-moosberger/quiz-data.js',
    },
    {
      id:          'david-1',
      title:       'DAVID 1',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--david-1',
      dataFile:    'sections/sprachbausteine-teil1/david-1/quiz-data.js',
    },
    {
      id:          'david-2',
      title:       'DAVID 2',
      description: 'Lückentext – Brief (Variante) · 10 Lücken',
      quizId:      'sprachbausteine-teil1--david-2',
      dataFile:    'sections/sprachbausteine-teil1/david-2/quiz-data.js',
    },
    {
      id:          'vanessa',
      title:       'VANESSA',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--vanessa',
      dataFile:    'sections/sprachbausteine-teil1/vanessa/quiz-data.js',
    },
    {
      id:          'chiara-mark',
      title:       'CHIARA & MARK',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--chiara-mark',
      dataFile:    'sections/sprachbausteine-teil1/chiara-mark/quiz-data.js',
    },
    {
      id:          'anna',
      title:       'ANNA',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--anna',
      dataFile:    'sections/sprachbausteine-teil1/anna/quiz-data.js',
    },
    {
      id:          'szabo-1',
      title:       'SZABO 1',
      description: 'Lückentext – Geschäftsbrief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--szabo-1',
      dataFile:    'sections/sprachbausteine-teil1/szabo-1/quiz-data.js',
    },
    {
      id:          'szabo-2',
      title:       'SZABO 2',
      description: 'Lückentext – Geschäftsbrief (Variante) · 10 Lücken',
      quizId:      'sprachbausteine-teil1--szabo-2',
      dataFile:    'sections/sprachbausteine-teil1/szabo-2/quiz-data.js',
    },
    {
      id:          'louise',
      title:       'LOUISE',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--louise',
      dataFile:    'sections/sprachbausteine-teil1/louise/quiz-data.js',
    },
    {
      id:          'goronsksa',
      title:       'GORONSKSA',
      description: 'Lückentext – Geschäftsbrief (Sprachurlaub) · 10 Lücken',
      quizId:      'sprachbausteine-teil1--goronsksa',
      dataFile:    'sections/sprachbausteine-teil1/goronsksa/quiz-data.js',
    },
    {
      id:          'andrea-1',
      title:       'ANDREA 1',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--andrea-1',
      dataFile:    'sections/sprachbausteine-teil1/andrea-1/quiz-data.js',
    },
    {
      id:          'andrea-2',
      title:       'ANDREA 2',
      description: 'Lückentext – Brief (Variante) · 10 Lücken',
      quizId:      'sprachbausteine-teil1--andrea-2',
      dataFile:    'sections/sprachbausteine-teil1/andrea-2/quiz-data.js',
    },
    {
      id:          'wenzel',
      title:       'WENZEL',
      description: 'Lückentext – Geschäftsbrief (Kulturbund) · 10 Lücken',
      quizId:      'sprachbausteine-teil1--wenzel',
      dataFile:    'sections/sprachbausteine-teil1/wenzel/quiz-data.js',
    },
    {
      id:          'cem',
      title:       'CEM',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--cem',
      dataFile:    'sections/sprachbausteine-teil1/cem/quiz-data.js',
    },
    {
      id:          'mercedes',
      title:       'MERCEDES',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--mercedes',
      dataFile:    'sections/sprachbausteine-teil1/mercedes/quiz-data.js',
    },
    {
      id:          'thomas',
      title:       'THOMAS',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--thomas',
      dataFile:    'sections/sprachbausteine-teil1/thomas/quiz-data.js',
    },
    {
      id:          'emilia',
      title:       'EMILIA',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--emilia',
      dataFile:    'sections/sprachbausteine-teil1/emilia/quiz-data.js',
    },
    {
      id:          'richard-justus',
      title:       'RICHARD (an Justus)',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--richard-justus',
      dataFile:    'sections/sprachbausteine-teil1/richard-justus/quiz-data.js',
    },
    {
      id:          'sarah',
      title:       'SARAH',
      description: 'Lückentext – Brief · 10 Lücken',
      quizId:      'sprachbausteine-teil1--sarah',
      dataFile:    'sections/sprachbausteine-teil1/sarah/quiz-data.js',
    },
  ],
});
