// ── Sprachbausteine Teil 2 – Section Config ────────────────────────────────
//
// HOW TO ADD A NEW TOPIC:
//   1. Create  sections/sprachbausteine-teil2/<topic-id>/quiz-data.js
//   2. Add a new entry to the topics[] array below
// ──────────────────────────────────────────────────────────────────────────

window.REGISTRY.push({
  id:       'sprachbausteine-teil2',
  title:    'Sprachbausteine Teil 2',
  subtitle: 'Das richtige Wort aus dem Kasten (A–O) in die Lücke einsetzen',
  topics: [
    {
      id:          'schulweg',
      title:       'SICHERER SCHULWEG',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--schulweg',
      dataFile:    'sections/sprachbausteine-teil2/schulweg/quiz-data.js',
    },
    {
      id:          'tv-bilder-fantasie',
      title:       'WIE TV-BILDER DIE FANTASIE VON KINDERN PRÄGEN',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--tv-bilder-fantasie',
      dataFile:    'sections/sprachbausteine-teil2/tv-bilder-fantasie/quiz-data.js',
    },
    {
      id:          'staedte-infarkt',
      title:       'STÄDTE VOR DEM INFARKT',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--staedte-infarkt',
      dataFile:    'sections/sprachbausteine-teil2/staedte-infarkt/quiz-data.js',
    },
    {
      id:          'garten-in-der-stadt',
      title:       'GARTEN IN DER STADT',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--garten-in-der-stadt',
      dataFile:    'sections/sprachbausteine-teil2/garten-in-der-stadt/quiz-data.js',
    },
    {
      id:          'obst-gemuese',
      title:       'WIE OBST UND GEMÜSE AUF UNSERE TELLER KOMMEN',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--obst-gemuese',
      dataFile:    'sections/sprachbausteine-teil2/obst-gemuese/quiz-data.js',
    },
    {
      id:          'fische-schlauer',
      title:       'FISCHE SIND SCHLAUER, ALS WIR DENKEN',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--fische-schlauer',
      dataFile:    'sections/sprachbausteine-teil2/fische-schlauer/quiz-data.js',
    },
    {
      id:          'katze-namen',
      title:       'WÄHLEN SIE DEN NAMEN IHRER KATZE MIT BEDACHT',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--katze-namen',
      dataFile:    'sections/sprachbausteine-teil2/katze-namen/quiz-data.js',
    },
    {
      id:          'im-restaurant-1',
      title:       'IM RESTAURANT 1',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--im-restaurant-1',
      dataFile:    'sections/sprachbausteine-teil2/im-restaurant-1/quiz-data.js',
    },
    {
      id:          'im-restaurant-2',
      title:       'IM RESTAURANT 2',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--im-restaurant-2',
      dataFile:    'sections/sprachbausteine-teil2/im-restaurant-2/quiz-data.js',
    },
    {
      id:          'ausbildung-ueber-30',
      title:       'AUSBILDUNG MIT ÜBER 30',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--ausbildung-ueber-30',
      dataFile:    'sections/sprachbausteine-teil2/ausbildung-ueber-30/quiz-data.js',
    },
    {
      id:          'hund-intelligentes-wesen',
      title:       'DER HUND ALS INTELLIGENTES WESEN',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--hund-intelligentes-wesen',
      dataFile:    'sections/sprachbausteine-teil2/hund-intelligentes-wesen/quiz-data.js',
    },
    {
      id:          'regeln-skipiste',
      title:       'DIE WICHTIGSTEN REGELN AUF DER SKIPISTE',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--regeln-skipiste',
      dataFile:    'sections/sprachbausteine-teil2/regeln-skipiste/quiz-data.js',
    },
    {
      id:          'lernen-kein-privileg',
      title:       'LERNEN IST KEIN PRIVILEG DER JUGEND',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--lernen-kein-privileg',
      dataFile:    'sections/sprachbausteine-teil2/lernen-kein-privileg/quiz-data.js',
    },
    {
      id:          'mann-kocht-selbst',
      title:       'MAN(N) KOCHT SELBST',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--mann-kocht-selbst',
      dataFile:    'sections/sprachbausteine-teil2/mann-kocht-selbst/quiz-data.js',
    },
    {
      id:          'kaffee-und-kuchen',
      title:       'KAFFEE UND KUCHEN – EIN STÜCK TRADITION',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--kaffee-und-kuchen',
      dataFile:    'sections/sprachbausteine-teil2/kaffee-und-kuchen/quiz-data.js',
    },
    {
      id:          'verlernen-hoeflichkeit',
      title:       'VERLERNEN DIE DEUTSCHEN DIE HÖFLICHKEIT?',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--verlernen-hoeflichkeit',
      dataFile:    'sections/sprachbausteine-teil2/verlernen-hoeflichkeit/quiz-data.js',
    },
    {
      id:          'schwarzarbeit',
      title:       'SCHWARZARBEIT KANN TEUER WERDEN',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--schwarzarbeit',
      dataFile:    'sections/sprachbausteine-teil2/schwarzarbeit/quiz-data.js',
    },
    {
      id:          'liebesgruesse-kuehltruhe',
      title:       'LIEBESGRÜSSE AUS DER KÜHLTRUHE',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--liebesgruesse-kuehltruhe',
      dataFile:    'sections/sprachbausteine-teil2/liebesgruesse-kuehltruhe/quiz-data.js',
    },
    {
      id:          'jugend-diskutiert',
      title:       'JUGEND DISKUTIERT – MACH MIT!',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--jugend-diskutiert',
      dataFile:    'sections/sprachbausteine-teil2/jugend-diskutiert/quiz-data.js',
    },
    {
      id:          'online-sprachkurse',
      title:       'ONLINE-SPRACHKURSE & CO.',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--online-sprachkurse',
      dataFile:    'sections/sprachbausteine-teil2/online-sprachkurse/quiz-data.js',
    },
    {
      id:          'bodyscanning-1',
      title:       'MAßGESCHNEIDERT NACH BODYSCANNING 1',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--bodyscanning-1',
      dataFile:    'sections/sprachbausteine-teil2/bodyscanning-1/quiz-data.js',
    },
    {
      id:          'bodyscanning-2',
      title:       'MAßGESCHNEIDERT NACH BODYSCANNING 2',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--bodyscanning-2',
      dataFile:    'sections/sprachbausteine-teil2/bodyscanning-2/quiz-data.js',
    },
    {
      id:          'klugste-freund-1',
      title:       'DER KLÜGSTE FREUND DES MENSCHEN 1',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--klugste-freund-1',
      dataFile:    'sections/sprachbausteine-teil2/klugste-freund-1/quiz-data.js',
    },
    {
      id:          'klugste-freund-2',
      title:       'DER KLÜGSTE FREUND DES MENSCHEN 2',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--klugste-freund-2',
      dataFile:    'sections/sprachbausteine-teil2/klugste-freund-2/quiz-data.js',
    },
    {
      id:          'manipulierte-bilder',
      title:       'MANIPULIERTE BILDER',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--manipulierte-bilder',
      dataFile:    'sections/sprachbausteine-teil2/manipulierte-bilder/quiz-data.js',
    },
    {
      id:          'was-steckt-bio',
      title:       'WAS STECKT HINTER "BIO"?',
      description: 'Wörter aus dem Kasten zuordnen · 10 Lücken',
      quizId:      'sprachbausteine-teil2--was-steckt-bio',
      dataFile:    'sections/sprachbausteine-teil2/was-steckt-bio/quiz-data.js',
    },
  ],
});
