// ── Leseverstehen Teil 1 – Section Config ──────────────────────────────────
//
// HOW TO ADD A NEW TOPIC:
//   1. Create  sections/leseverstehen-teil1/<topic-id>/quiz-data.js
//   2. Add a new entry to the topics[] array below
// ──────────────────────────────────────────────────────────────────────────

window.REGISTRY.push({
  id:       'leseverstehen-teil1',
  title:    'Leseverstehen Teil 1',
  subtitle: 'Einen passenden Text zu einer Überschrift zuordnen',
  topics: [
    {
      id:          'schule',
      title:       'SCHULE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--schule',
      dataFile:    'sections/leseverstehen-teil1/schule/quiz-data.js',
    },
    {
      id:          'spielzeug',
      title:       'SPIELZEUG',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--spielzeug',
      dataFile:    'sections/leseverstehen-teil1/spielzeug/quiz-data.js',
    },
    {
      id:          'limonade',
      title:       'LIMONADE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--limonade',
      dataFile:    'sections/leseverstehen-teil1/limonade/quiz-data.js',
    },
    {
      id:          'inseln',
      title:       'INSELN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--inseln',
      dataFile:    'sections/leseverstehen-teil1/inseln/quiz-data.js',
    },

    // NEW TOPICS
    {
      id:          'beruf',
      title:       'BERUF',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--beruf',
      dataFile:    'sections/leseverstehen-teil1/beruf/quiz-data.js',
    },
    {
      id:          'fotografie',
      title:       'FOTOGRAFIE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--fotografie',
      dataFile:    'sections/leseverstehen-teil1/fotografie/quiz-data.js',
    },
    {
      id:          'gemuese',
      title:       'GEMÜSE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--gemuese',
      dataFile:    'sections/leseverstehen-teil1/gemuese/quiz-data.js',
    },
    {
      id:          'grippe',
      title:       'GRIPPE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--grippe',
      dataFile:    'sections/leseverstehen-teil1/grippe/quiz-data.js',
    },
    {
      id:          'insekten',
      title:       'INSEKTEN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--insekten',
      dataFile:    'sections/leseverstehen-teil1/insekten/quiz-data.js',
    },
    {
      id:          'jugend',
      title:       'JUGEND',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--jugend',
      dataFile:    'sections/leseverstehen-teil1/jugend/quiz-data.js',
    },
    {
      id:          'maerkte',
      title:       'MÄRKTE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--maerkte',
      dataFile:    'sections/leseverstehen-teil1/maerkte/quiz-data.js',
    },
    {
      id:          'tanzkurs',
      title:       'TANZKURS',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--tanzkurs',
      dataFile:    'sections/leseverstehen-teil1/tanzkurs/quiz-data.js',
    },
    {
      id:          'zigarette1',
      title:       'ZIGARETTE 1',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--zigarette1',
      dataFile:    'sections/leseverstehen-teil1/zigarette1/quiz-data.js',
    },
    {
      id:          'zigarette2',
      title:       'ZIGARETTE 2',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--zigarette2',
      dataFile:    'sections/leseverstehen-teil1/zigarette2/quiz-data.js',
    },
    {
      id:          'suesswaren',
      title:       'SÜSSWAREN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--suesswaren',
      dataFile:    'sections/leseverstehen-teil1/suesswaren/quiz-data.js',
    },
    {
      id:          'finanzen',
      title:       'FINANZEN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--finanzen',
      dataFile:    'sections/leseverstehen-teil1/finanzen/quiz-data.js',
    },
    {
      id:          'trampolin',
      title:       'TRAMPOLIN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--trampolin',
      dataFile:    'sections/leseverstehen-teil1/trampolin/quiz-data.js',
    },
    {
      id:          'geruch',
      title:       'GERUCH',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--geruch',
      dataFile:    'sections/leseverstehen-teil1/geruch/quiz-data.js',
    },
    {
      id:          'kunstlicht',
      title:       'KUNSTLICHT',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--kunstlicht',
      dataFile:    'sections/leseverstehen-teil1/kunstlicht/quiz-data.js',
    },
    {
      id:          'kaffee',
      title:       'KAFFEE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--kaffee',
      dataFile:    'sections/leseverstehen-teil1/kaffee/quiz-data.js',
    },
    {
      id:          'benzin',
      title:       'BENZIN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--benzin',
      dataFile:    'sections/leseverstehen-teil1/benzin/quiz-data.js',
    },
    {
      id:          'sport',
      title:       'SPORT',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--sport',
      dataFile:    'sections/leseverstehen-teil1/sport/quiz-data.js',
    },
    {
      id:          'partner',
      title:       'PARTNER',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--partner',
      dataFile:    'sections/leseverstehen-teil1/partner/quiz-data.js',
    },
    {
      id:          'einschulung',
      title:       'EINSCHULUNG',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--einschulung',
      dataFile:    'sections/leseverstehen-teil1/einschulung/quiz-data.js',
    },
    {
      id:          'bienen',
      title:       'BIENEN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--bienen',
      dataFile:    'sections/leseverstehen-teil1/bienen/quiz-data.js',
    },
    {
      id:          'tauchen',
      title:       'TAUCHEN',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--tauchen',
      dataFile:    'sections/leseverstehen-teil1/tauchen/quiz-data.js',
    },
    {
      id:          'online',
      title:       'ONLINE',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--online',
      dataFile:    'sections/leseverstehen-teil1/online/quiz-data.js',
    },
    {
      id:          'wahlrecht',
      title:       'WAHLRECHT',
      description: 'Überschrift finden · 5 Texte',
      quizId:      'leseverstehen-teil1--wahlrecht',
      dataFile:    'sections/leseverstehen-teil1/wahlrecht/quiz-data.js',
    },

  ],
});